version: 2
jobs:
  build:
    docker:
      - image: circleci/node:latest
    resource_class: massive
    parallelism: 2
    steps:
      - checkout

workflows:
  version: 2
  app:
    jobs:
      - build
